#  This file is for data cleaning of the csgo_round_snapshots.csv

In [1]:
import pandas as pd
import numpy as np
from sklearn.preprocessing import LabelEncoder

In [2]:
data_train = pd.read_csv('cs_go_winner_data_train.csv')
data_test = pd.read_csv('cs_go_winner_data_test.csv')

In [3]:
data_train.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 97928 entries, 0 to 97927
Data columns (total 97 columns):
 #   Column                        Non-Null Count  Dtype
---  ------                        --------------  -----
 0   time_left                     97928 non-null  float64
 1   ct_score                      97928 non-null  float64
 2   t_score                       97928 non-null  float64
 3   map                           97928 non-null  object
 4   bomb_planted                  97928 non-null  bool
 5   ct_health                     97928 non-null  float64
 6   t_health                      97928 non-null  float64
 7   ct_armor                      97928 non-null  float64
 8   t_armor                       97928 non-null  float64
 9   ct_money                      97928 non-null  float64
 10  t_money                       97928 non-null  float64
 11  ct_helmets                    97928 non-null  float64
 12  t_helmets                     97928 non-null  float64
 13  ct_defuse_kits                97928 non-null  float64
 14  ct_players_alive              97928 non-null  float64
 15  t_players_alive               97928 non-null  float64
 16  ct_weapon_ak47                97928 non-null  float64
 17  t_weapon_ak47                 97928 non-null  float64
 18  ct_weapon_aug                 97928 non-null  float64
 19  t_weapon_aug                  97928 non-null  float64
 20  ct_weapon_awp                 97928 non-null  float64
 21  t_weapon_awp                  97928 non-null  float64
 22  ct_weapon_bizon               97928 non-null  float64
 23  t_weapon_bizon                97928 non-null  float64
 24  ct_weapon_cz75auto            97928 non-null  float64
 25  t_weapon_cz75auto             97928 non-null  float64
 26  ct_weapon_elite               97928 non-null  float64
 27  t_weapon_elite                97928 non-null  float64
 28  ct_weapon_famas               97928 non-null  float64
 29  t_weapon_famas                97928 non-null  float64
 30  ct_weapon_g3sg1               97928 non-null  float64
 31  t_weapon_g3sg1                97928 non-null  float64
 32  ct_weapon_galilar             97928 non-null  float64
 33  t_weapon_galilar              97928 non-null  float64
 34  ct_weapon_glock               97928 non-null  float64
 35  t_weapon_glock                97928 non-null  float64
 36  ct_weapon_m249                97928 non-null  float64
 37  t_weapon_m249                 97928 non-null  float64
 38  ct_weapon_m4a1s               97928 non-null  float64
 39  t_weapon_m4a1s                97928 non-null  float64
 40  ct_weapon_m4a4                97928 non-null  float64
 41  t_weapon_m4a4                 97928 non-null  float64
 42  ct_weapon_mac10               97928 non-null  float64
 43  t_weapon_mac10                97928 non-null  float64
 44  ct_weapon_mag7                97928 non-null  float64
 45  t_weapon_mag7                 97928 non-null  float64
 46  ct_weapon_mp5sd               97928 non-null  float64
 47  t_weapon_mp5sd                97928 non-null  float64
 48  ct_weapon_mp7                 97928 non-null  float64
 49  t_weapon_mp7                  97928 non-null  float64
 50  ct_weapon_mp9                 97928 non-null  float64
 51  t_weapon_mp9                  97928 non-null  float64
 52  ct_weapon_negev               97928 non-null  float64
 53  t_weapon_negev                97928 non-null  float64
 54  ct_weapon_nova                97928 non-null  float64
 55  t_weapon_nova                 97928 non-null  float64
 56  ct_weapon_p90                 97928 non-null  float64
 57  t_weapon_p90                  97928 non-null  float64
 58  ct_weapon_r8revolver          97928 non-null  float64
 59  t_weapon_r8revolver           97928 non-null  float64
 60  ct_weapon_sawedoff            97928 non-null  float64
 61  t_weapon_sawedoff             97928 non-null  float64
 62  ct_weapon_scar20              97928 non-null  float64
 63  t_weapon_scar20               97928 non-null  float64
 64  ct_weapon_sg553               97928 non-null  float64
 65  t_weapon_sg553                97928 non-null  float64
 66  ct_weapon_ssg08               97928 non-null  float64
 67  t_weapon_ssg08                97928 non-null  float64
 68  ct_weapon_ump45               97928 non-null  float64
 69  t_weapon_ump45                97928 non-null  float64
 70  ct_weapon_xm1014              97928 non-null  float64
 71  t_weapon_xm1014               97928 non-null  float64
 72  ct_weapon_deagle              97928 non-null  float64
 73  t_weapon_deagle               97928 non-null  float64
 74  ct_weapon_fiveseven           97928 non-null  float64
 75  t_weapon_fiveseven            97928 non-null  float64
 76  ct_weapon_usps                97928 non-null  float64
 77  t_weapon_usps                 97928 non-null  float64
 78  ct_weapon_p250                97928 non-null  float64
 79  t_weapon_p250                 97928 non-null  float64
 80  ct_weapon_p2000               97928 non-null  float64
 81  t_weapon_p2000                97928 non-null  float64
 82  ct_weapon_tec9                97928 non-null  float64
 83  t_weapon_tec9                 97928 non-null  float64
 84  ct_grenade_hegrenade          97928 non-null  float64
 85  t_grenade_hegrenade           97928 non-null  float64
 86  ct_grenade_flashbang          97928 non-null  float64
 87  t_grenade_flashbang           97928 non-null  float64
 88  ct_grenade_smokegrenade       97928 non-null  float64
 89  t_grenade_smokegrenade        97928 non-null  float64
 90  ct_grenade_incendiarygrenade  97928 non-null  float64
 91  t_grenade_incendiarygrenade   97928 non-null  float64
 92  ct_grenade_molotovgrenade     97928 non-null  float64
 93  t_grenade_molotovgrenade      97928 non-null  float64
 94  ct_grenade_decoygrenade       97928 non-null  float64
 95  t_grenade_decoygrenade        97928 non-null  float64
 96  round_winner                  97928 non-null  object
dtypes: bool(1), float64(94), object(2)
memory usage: 71.8+ MB

In [4]:
data_test.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 24482 entries, 0 to 24481
Data columns (total 97 columns):
 #   Column                        Non-Null Count  Dtype
---  ------                        --------------  -----
 0   time_left                     24482 non-null  float64
 1   ct_score                      24482 non-null  float64
 2   t_score                       24482 non-null  float64
 3   map                           24482 non-null  object
 4   bomb_planted                  24482 non-null  bool
 5   ct_health                     24482 non-null  float64
 6   t_health                      24482 non-null  float64
 7   ct_armor                      24482 non-null  float64
 8   t_armor                       24482 non-null  float64
 9   ct_money                      24482 non-null  float64
 10  t_money                       24482 non-null  float64
 11  ct_helmets                    24482 non-null  float64
 12  t_helmets                     24482 non-null  float64
 13  ct_defuse_kits                24482 non-null  float64
 14  ct_players_alive              24482 non-null  float64
 15  t_players_alive               24482 non-null  float64
 16  ct_weapon_ak47                24482 non-null  float64
 17  t_weapon_ak47                 24482 non-null  float64
 18  ct_weapon_aug                 24482 non-null  float64
 19  t_weapon_aug                  24482 non-null  float64
 20  ct_weapon_awp                 24482 non-null  float64
 21  t_weapon_awp                  24482 non-null  float64
 22  ct_weapon_bizon               24482 non-null  float64
 23  t_weapon_bizon                24482 non-null  float64
 24  ct_weapon_cz75auto            24482 non-null  float64
 25  t_weapon_cz75auto             24482 non-null  float64
 26  ct_weapon_elite               24482 non-null  float64
 27  t_weapon_elite                24482 non-null  float64
 28  ct_weapon_famas               24482 non-null  float64
 29  t_weapon_famas                24482 non-null  float64
 30  ct_weapon_g3sg1               24482 non-null  float64
 31  t_weapon_g3sg1                24482 non-null  float64
 32  ct_weapon_galilar             24482 non-null  float64
 33  t_weapon_galilar              24482 non-null  float64
 34  ct_weapon_glock               24482 non-null  float64
 35  t_weapon_glock                24482 non-null  float64
 36  ct_weapon_m249                24482 non-null  float64
 37  t_weapon_m249                 24482 non-null  float64
 38  ct_weapon_m4a1s               24482 non-null  float64
 39  t_weapon_m4a1s                24482 non-null  float64
 40  ct_weapon_m4a4                24482 non-null  float64
 41  t_weapon_m4a4                 24482 non-null  float64
 42  ct_weapon_mac10               24482 non-null  float64
 43  t_weapon_mac10                24482 non-null  float64
 44  ct_weapon_mag7                24482 non-null  float64
 45  t_weapon_mag7                 24482 non-null  float64
 46  ct_weapon_mp5sd               24482 non-null  float64
 47  t_weapon_mp5sd                24482 non-null  float64
 48  ct_weapon_mp7                 24482 non-null  float64
 49  t_weapon_mp7                  24482 non-null  float64
 50  ct_weapon_mp9                 24482 non-null  float64
 51  t_weapon_mp9                  24482 non-null  float64
 52  ct_weapon_negev               24482 non-null  float64
 53  t_weapon_negev                24482 non-null  float64
 54  ct_weapon_nova                24482 non-null  float64
 55  t_weapon_nova                 24482 non-null  float64
 56  ct_weapon_p90                 24482 non-null  float64
 57  t_weapon_p90                  24482 non-null  float64
 58  ct_weapon_r8revolver          24482 non-null  float64
 59  t_weapon_r8revolver           24482 non-null  float64
 60  ct_weapon_sawedoff            24482 non-null  float64
 61  t_weapon_sawedoff             24482 non-null  float64
 62  ct_weapon_scar20              24482 non-null  float64
 63  t_weapon_scar20               24482 non-null  float64
 64  ct_weapon_sg553               24482 non-null  float64
 65  t_weapon_sg553                24482 non-null  float64
 66  ct_weapon_ssg08               24482 non-null  float64
 67  t_weapon_ssg08                24482 non-null  float64
 68  ct_weapon_ump45               24482 non-null  float64
 69  t_weapon_ump45                24482 non-null  float64
 70  ct_weapon_xm1014              24482 non-null  float64
 71  t_weapon_xm1014               24482 non-null  float64
 72  ct_weapon_deagle              24482 non-null  float64
 73  t_weapon_deagle               24482 non-null  float64
 74  ct_weapon_fiveseven           24482 non-null  float64
 75  t_weapon_fiveseven            24482 non-null  float64
 76  ct_weapon_usps                24482 non-null  float64
 77  t_weapon_usps                 24482 non-null  float64
 78  ct_weapon_p250                24482 non-null  float64
 79  t_weapon_p250                 24482 non-null  float64
 80  ct_weapon_p2000               24482 non-null  float64
 81  t_weapon_p2000                24482 non-null  float64
 82  ct_weapon_tec9                24482 non-null  float64
 83  t_weapon_tec9                 24482 non-null  float64
 84  ct_grenade_hegrenade          24482 non-null  float64
 85  t_grenade_hegrenade           24482 non-null  float64
 86  ct_grenade_flashbang          24482 non-null  float64
 87  t_grenade_flashbang           24482 non-null  float64
 88  ct_grenade_smokegrenade       24482 non-null  float64
 89  t_grenade_smokegrenade        24482 non-null  float64
 90  ct_grenade_incendiarygrenade  24482 non-null  float64
 91  t_grenade_incendiarygrenade   24482 non-null  float64
 92  ct_grenade_molotovgrenade     24482 non-null  float64
 93  t_grenade_molotovgrenade      24482 non-null  float64
 94  ct_grenade_decoygrenade       24482 non-null  float64
 95  t_grenade_decoygrenade        24482 non-null  float64
 96  round_winner                  24482 non-null  object
dtypes: bool(1), float64(94), object(2)
memory usage: 18.0+ MB

In [5]:
data_train.describe()

,time_left,ct_score,t_score,ct_health,t_health,ct_armor,t_armor,ct_money,t_money,ct_helmets,...,ct_grenade_flashbang,t_grenade_flashbang,ct_grenade_smokegrenade,t_grenade_smokegrenade,ct_grenade_incendiarygrenade,t_grenade_incendiarygrenade,ct_grenade_molotovgrenade,t_grenade_molotovgrenade,ct_grenade_decoygrenade,t_grenade_decoygrenade
count,97928.000000,97928.000000,97928.000000,97928.000000,97928.000000,97928.000000,97928.000000,97928.000000,97928.000000,97928.00000,...,97928.000000,97928.000000,97928.000000,97928.000000,97928.000000,97928.000000,97928.000000,97928.000000,97928.000000,97928.000000
mean,97.813151,6.706090,6.778592,412.083286,402.698135,314.620098,298.976718,9764.438669,11228.156911,2.05502,...,1.856966,1.859264,1.545799,1.626889,1.005014,0.019810,0.047851,1.354607,0.027827,0.025937
std,54.405312,4.791153,4.817133,132.169190,139.939050,170.779443,174.462849,11183.453026,12168.532786,1.84162,...,1.773360,1.794622,1.739222,1.828452,1.460676,0.143821,0.226768,1.664179,0.170033,0.164382
min,0.010000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.00000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,54.920000,3.000000,3.000000,351.000000,322.000000,194.000000,175.000000,1300.000000,1550.000000,0.00000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
50%,94.910000,6.000000,6.000000,500.000000,500.000000,378.000000,336.000000,5450.000000,7100.000000,2.00000,...,1.000000,1.000000,1.000000,1.000000,0.000000,0.000000,0.000000,1.000000,0.000000,0.000000
75%,166.910000,10.000000,10.000000,500.000000,500.000000,486.000000,468.000000,14550.000000,18000.000000,4.00000,...,3.000000,3.000000,3.000000,3.000000,2.000000,0.000000,0.000000,2.000000,0.000000,0.000000
max,175.000000,32.000000,33.000000,500.000000,600.000000,500.000000,500.000000,80000.000000,80000.000000,5.00000,...,7.000000,5.000000,6.000000,5.000000,5.000000,3.000000,3.000000,5.000000,3.000000,2.000000

In [6]:
data_test.describe()

,time_left,ct_score,t_score,ct_health,t_health,ct_armor,t_armor,ct_money,t_money,ct_helmets,...,ct_grenade_flashbang,t_grenade_flashbang,ct_grenade_smokegrenade,t_grenade_smokegrenade,ct_grenade_incendiarygrenade,t_grenade_incendiarygrenade,ct_grenade_molotovgrenade,t_grenade_molotovgrenade,ct_grenade_decoygrenade,t_grenade_decoygrenade
count,24482.000000,24482.000000,24482.000000,24482.000000,24482.000000,24482.000000,24482.000000,24482.000000,24482.000000,24482.000000,...,24482.000000,24482.000000,24482.000000,24482.000000,24482.000000,24482.000000,24482.000000,24482.000000,24482.000000,24482.000000
mean,98.182007,6.721836,6.787803,412.199698,402.779961,312.230210,296.316477,9887.364186,11292.555755,2.049424,...,1.837922,1.853443,1.520872,1.628176,0.989788,0.019851,0.048648,1.342047,0.027163,0.024998
std,54.704407,4.787275,4.849193,132.791196,139.841775,172.017484,175.017987,11340.216773,12139.987169,1.840902,...,1.770466,1.793905,1.732013,1.831962,1.447634,0.144384,0.231241,1.659506,0.167511,0.163284
min,0.060000,0.000000,0.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,54.920000,3.000000,3.000000,349.000000,322.000000,192.000000,171.000000,1300.000000,1650.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
50%,94.920000,6.000000,6.000000,500.000000,500.000000,374.000000,326.000000,5500.000000,7300.000000,2.000000,...,1.000000,1.000000,1.000000,1.000000,0.000000,0.000000,0.000000,1.000000,0.000000,0.000000
75%,167.000000,10.000000,10.000000,500.000000,500.000000,486.000000,466.000000,14800.000000,18100.000000,4.000000,...,3.000000,3.000000,3.000000,3.000000,2.000000,0.000000,0.000000,2.000000,0.000000,0.000000
max,175.000000,32.000000,33.000000,500.000000,500.000000,500.000000,500.000000,80000.000000,80000.000000,5.000000,...,6.000000,7.000000,5.000000,9.000000,5.000000,3.000000,3.000000,5.000000,3.000000,2.000000

In [7]:
pd.set_option('display.max_rows', None)
np.sum(data_train.isnull())

/opt/anaconda3/envs/usc_ml/lib/python3.12/site-packages/numpy/core/fromnumeric.py:86: FutureWarning: The behavior of DataFrame.sum with axis=None is deprecated, in a future version this will reduce over both axes and return a scalar. To retain the old behavior, pass axis=0 (or do not pass axis)
  return reduction(axis=axis, out=out, **passkwargs)

time_left                       0
ct_score                        0
t_score                         0
map                             0
bomb_planted                    0
ct_health                       0
t_health                        0
ct_armor                        0
t_armor                         0
ct_money                        0
t_money                         0
ct_helmets                      0
t_helmets                       0
ct_defuse_kits                  0
ct_players_alive                0
t_players_alive                 0
ct_weapon_ak47                  0
t_weapon_ak47                   0
ct_weapon_aug                   0
t_weapon_aug                    0
ct_weapon_awp                   0
t_weapon_awp                    0
ct_weapon_bizon                 0
t_weapon_bizon                  0
ct_weapon_cz75auto              0
t_weapon_cz75auto               0
ct_weapon_elite                 0
t_weapon_elite                  0
ct_weapon_famas                 0
t_weapon_famas                  0
ct_weapon_g3sg1                 0
t_weapon_g3sg1                  0
ct_weapon_galilar               0
t_weapon_galilar                0
ct_weapon_glock                 0
t_weapon_glock                  0
ct_weapon_m249                  0
t_weapon_m249                   0
ct_weapon_m4a1s                 0
t_weapon_m4a1s                  0
ct_weapon_m4a4                  0
t_weapon_m4a4                   0
ct_weapon_mac10                 0
t_weapon_mac10                  0
ct_weapon_mag7                  0
t_weapon_mag7                   0
ct_weapon_mp5sd                 0
t_weapon_mp5sd                  0
ct_weapon_mp7                   0
t_weapon_mp7                    0
ct_weapon_mp9                   0
t_weapon_mp9                    0
ct_weapon_negev                 0
t_weapon_negev                  0
ct_weapon_nova                  0
t_weapon_nova                   0
ct_weapon_p90                   0
t_weapon_p90                    0
ct_weapon_r8revolver            0
t_weapon_r8revolver             0
ct_weapon_sawedoff              0
t_weapon_sawedoff               0
ct_weapon_scar20                0
t_weapon_scar20                 0
ct_weapon_sg553                 0
t_weapon_sg553                  0
ct_weapon_ssg08                 0
t_weapon_ssg08                  0
ct_weapon_ump45                 0
t_weapon_ump45                  0
ct_weapon_xm1014                0
t_weapon_xm1014                 0
ct_weapon_deagle                0
t_weapon_deagle                 0
ct_weapon_fiveseven             0
t_weapon_fiveseven              0
ct_weapon_usps                  0
t_weapon_usps                   0
ct_weapon_p250                  0
t_weapon_p250                   0
ct_weapon_p2000                 0
t_weapon_p2000                  0
ct_weapon_tec9                  0
t_weapon_tec9                   0
ct_grenade_hegrenade            0
t_grenade_hegrenade             0
ct_grenade_flashbang            0
t_grenade_flashbang             0
ct_grenade_smokegrenade         0
t_grenade_smokegrenade          0
ct_grenade_incendiarygrenade    0
t_grenade_incendiarygrenade     0
ct_grenade_molotovgrenade       0
t_grenade_molotovgrenade        0
ct_grenade_decoygrenade         0
t_grenade_decoygrenade          0
round_winner                    0
dtype: int64

In [8]:
pd.set_option('display.max_rows', None)
np.sum(data_test.isnull())

time_left                       0
ct_score                        0
t_score                         0
map                             0
bomb_planted                    0
ct_health                       0
t_health                        0
ct_armor                        0
t_armor                         0
ct_money                        0
t_money                         0
ct_helmets                      0
t_helmets                       0
ct_defuse_kits                  0
ct_players_alive                0
t_players_alive                 0
ct_weapon_ak47                  0
t_weapon_ak47                   0
ct_weapon_aug                   0
t_weapon_aug                    0
ct_weapon_awp                   0
t_weapon_awp                    0
ct_weapon_bizon                 0
t_weapon_bizon                  0
ct_weapon_cz75auto              0
t_weapon_cz75auto               0
ct_weapon_elite                 0
t_weapon_elite                  0
ct_weapon_famas                 0
t_weapon_famas                  0
ct_weapon_g3sg1                 0
t_weapon_g3sg1                  0
ct_weapon_galilar               0
t_weapon_galilar                0
ct_weapon_glock                 0
t_weapon_glock                  0
ct_weapon_m249                  0
t_weapon_m249                   0
ct_weapon_m4a1s                 0
t_weapon_m4a1s                  0
ct_weapon_m4a4                  0
t_weapon_m4a4                   0
ct_weapon_mac10                 0
t_weapon_mac10                  0
ct_weapon_mag7                  0
t_weapon_mag7                   0
ct_weapon_mp5sd                 0
t_weapon_mp5sd                  0
ct_weapon_mp7                   0
t_weapon_mp7                    0
ct_weapon_mp9                   0
t_weapon_mp9                    0
ct_weapon_negev                 0
t_weapon_negev                  0
ct_weapon_nova                  0
t_weapon_nova                   0
ct_weapon_p90                   0
t_weapon_p90                    0
ct_weapon_r8revolver            0
t_weapon_r8revolver             0
ct_weapon_sawedoff              0
t_weapon_sawedoff               0
ct_weapon_scar20                0
t_weapon_scar20                 0
ct_weapon_sg553                 0
t_weapon_sg553                  0
ct_weapon_ssg08                 0
t_weapon_ssg08                  0
ct_weapon_ump45                 0
t_weapon_ump45                  0
ct_weapon_xm1014                0
t_weapon_xm1014                 0
ct_weapon_deagle                0
t_weapon_deagle                 0
ct_weapon_fiveseven             0
t_weapon_fiveseven              0
ct_weapon_usps                  0
t_weapon_usps                   0
ct_weapon_p250                  0
t_weapon_p250                   0
ct_weapon_p2000                 0
t_weapon_p2000                  0
ct_weapon_tec9                  0
t_weapon_tec9                   0
ct_grenade_hegrenade            0
t_grenade_hegrenade             0
ct_grenade_flashbang            0
t_grenade_flashbang             0
ct_grenade_smokegrenade         0
t_grenade_smokegrenade          0
ct_grenade_incendiarygrenade    0
t_grenade_incendiarygrenade     0
ct_grenade_molotovgrenade       0
t_grenade_molotovgrenade        0
ct_grenade_decoygrenade         0
t_grenade_decoygrenade          0
round_winner                    0
dtype: int64

### Encode non-numerical binary/non-binary representations of to using numbers

In [9]:
# One-hot encode the categorical columns
data_train = pd.get_dummies(data_train, columns=['map'], drop_first=False)
data_test = pd.get_dummies(data_test, columns=['map'], drop_first=False)

In [10]:
encoder = LabelEncoder()

# Maps
data_train['map_de_cache'] = encoder.fit_transform(data_train['map_de_cache'])
map_mappings = {index : label for index, label in enumerate(encoder.classes_)}

data_train['map_de_dust2'] = encoder.fit_transform(data_train['map_de_dust2'])
map_mappings = {index : label for index, label in enumerate(encoder.classes_)}

data_train['map_de_inferno'] = encoder.fit_transform(data_train['map_de_inferno'])
map_mappings = {index : label for index, label in enumerate(encoder.classes_)}

data_train['map_de_mirage'] = encoder.fit_transform(data_train['map_de_mirage'])
map_mappings = {index : label for index, label in enumerate(encoder.classes_)}

data_train['map_de_nuke'] = encoder.fit_transform(data_train['map_de_nuke'])
map_mappings = {index : label for index, label in enumerate(encoder.classes_)}

data_train['map_de_overpass'] = encoder.fit_transform(data_train['map_de_overpass'])
map_mappings = {index : label for index, label in enumerate(encoder.classes_)}

data_train['map_de_train'] = encoder.fit_transform(data_train['map_de_train'])
map_mappings = {index : label for index, label in enumerate(encoder.classes_)}

data_train['map_de_vertigo'] = encoder.fit_transform(data_train['map_de_vertigo'])
map_mappings = {index : label for index, label in enumerate(encoder.classes_)}

data_test['map_de_cache'] = encoder.fit_transform(data_test['map_de_cache'])
map_mappings = {index : label for index, label in enumerate(encoder.classes_)}

data_test['map_de_dust2'] = encoder.fit_transform(data_test['map_de_dust2'])
map_mappings = {index : label for index, label in enumerate(encoder.classes_)}

data_test['map_de_inferno'] = encoder.fit_transform(data_test['map_de_inferno'])
map_mappings = {index : label for index, label in enumerate(encoder.classes_)}

data_test['map_de_mirage'] = encoder.fit_transform(data_test['map_de_mirage'])
map_mappings = {index : label for index, label in enumerate(encoder.classes_)}

data_test['map_de_nuke'] = encoder.fit_transform(data_test['map_de_nuke'])
map_mappings = {index : label for index, label in enumerate(encoder.classes_)}

data_test['map_de_overpass'] = encoder.fit_transform(data_test['map_de_overpass'])
map_mappings = {index : label for index, label in enumerate(encoder.classes_)}

data_test['map_de_train'] = encoder.fit_transform(data_test['map_de_train'])
map_mappings = {index : label for index, label in enumerate(encoder.classes_)}

data_test['map_de_vertigo'] = encoder.fit_transform(data_test['map_de_vertigo'])
map_mappings = {index : label for index, label in enumerate(encoder.classes_)}

# Round winner
round_winner_mappings = {'CT': 1, 'T': -1}
data_train['round_winner'] = data_train['round_winner'].map(round_winner_mappings)
data_test['round_winner'] = data_test['round_winner'].map(round_winner_mappings)

# Bomb planted
data_train['bomb_planted'] = encoder.fit_transform(data_train['bomb_planted'])
bomb_planted_mappings = {index : label for index, label in enumerate(encoder.classes_)}
data_test['bomb_planted'] = encoder.fit_transform(data_test['bomb_planted'])
bomb_planted_mappings = {index : label for index, label in enumerate(encoder.classes_)}

print(map_mappings)
print(round_winner_mappings)
print(bomb_planted_mappings)

{0: False, 1: True}
{'CT': 1, 'T': -1}
{0: False, 1: True}

## Save to folder

In [11]:
# Save data to local folder with a new name
data_train.to_csv('train_cleaned.csv', index=False)

In [12]:
data_test.to_csv('test_cleaned.csv', index=False)

In [13]:
data_test.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 24482 entries, 0 to 24481
Columns: 104 entries, time_left to map_de_vertigo
dtypes: float64(94), int64(10)
memory usage: 19.4 MB